### ISSUE TITLE
How do I submit modifications to this project?

### ISSUE THREAD

**Issue by luarvique** [SDRplay/ExtIO_SDRplay#1]
Fixed RSPduo switch between tuners. Where do I submit my changes?

**Comment by SDRplay** [comment]
Please submit a pull request with your changes.
Best regards,
SDRplay

**Comment by luarvique** [comment]
Cannot submit a pull request without creating a branch first. Cannot create a branch from your repository, since it does not appear to allow this.

**Comment by SDRplay** [comment]
You just fork the repository and then submit a pull request using that
