### ISSUE TITLE
StartHW() missing actually setting the freq

### ISSUE THREAD

**Issue by jazzkutya** [SDRplay/ExtIO_SDRplay#1]
Hi,

I think StartHW() is missing a line to actually set the frequency. It should do
Frequency = (double)freq / 1000000;
somewhere, and maybe all the other stuff SetHWLO() does.
That said, i did not get any actual problem due to this, it seems all app i tried yet does a SetHWLO() after StartHW().

**Comment by SDRplay** [comment]
SetHWLO() is always called before StartHW to set the Frequency. All StartHW() does it literally run an initialise to start the hardware.
